{
 "title": "RED",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "API Call Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/resourceReferential\"}[5m])"
    }
   ]
  },
  {
   "title": "API calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/resourceReferential\"}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/resourceReferential\", status!~\"2..\"}[5m])"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/resourceReferential\"}[1m]) / rate(http_server_requests_seconds_count{uri=\"/resourceReferential\"}[1m])"
    }
   ]
  }
 ]
}